### ISSUE TITLE
How to specify a route with a dash in the locales.json?

### ISSUE THREAD

**Issue by vasrot** [gilsdav/angular-universal-localize-router#12]
I was looking a month already and I haven't found a thing. 
For example, if I have a route that's something like this = 'find-user'.
Should I name it like this in the ROUTES locales -> "ROUTES.find-user": "find-user"   or like this "ROUTES['find-user']": "find-user",

Thank you.

**Comment by gilsdav** [comment]
Hello @vasrot 
You can use
```
"ROUTES.find-user": "find-user"
```
or
```
"ROUTES": {
    "find-user": "find-user"
}
```
The two works fine for me.
