### ISSUE TITLE
not working url

### ISSUE THREAD

**Issue by nikolay-kovalenko** [gilsdav/angular-universal-localize-router#8]
```
  <a *ngFor="let hero of heroes" class="col-1-4" 
      routerLink="/detail/{{hero.id}}"> here dashboard.component.html
```
**My fix:**
**in here dashboard.component.html and** 
`[routerLink]=" translateUrl('/detail/') + '/' + hero.id" ` 

**in dashboard.component.ts**
```
  translateUrl(route: string) {
    return this.localizeService.translateRoute(route);
  }
```

**Comment by 6matko** [comment]
Or ```routerLink="{{'/detail' | localize}}/{{hero.id}}"```

**Comment by gilsdav** [comment]
For sure, I didn't fixed all of the urls but you only need to use the `| localize` pipe.
```
 routerLink="['/detail', hero.id] | localize"
```
